export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SERVER_RESPONSE_ERROR =
  "SIGNUP_USER_SERVER_RESPONSE_ERROR";
export const SIGNUP_USER_SERVER_RESPONSE_SUCCESS =
  "SIGNUP_USER_SERVER_RESPONSE_SUCCESS";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SERVER_RESPONSE_ERROR =
  "LOGIN_USER_SERVER_RESPONSE_ERROR";
export const LOGIN_USER_SERVER_RESPONSE_SUCCESS =
  "LOGIN_USER_SERVER_RESPONSE_SUCCESS";

export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const CREATE_ARTICLE_DETAILS_SERVER_RESPONSE_SUCCESS =
  "CREATE_ARTICLE_DETAILS_SERVER_RESPONSE_SUCCESS";
export const CREATE_ARTICLE_DETAILS_SERVER_RESPONSE_ERROR =
  "CREATE_ARTICLE_DETAILS_SERVER_RESPONSE_ERROR";

export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";

export const ARTICLE = "ARTICLE";
export const ARTICLE_SUCCESS_RESPONSE = "ARTICLE_SUCCESS_RESPONSE";
export const ARTICLE_ERROR_RESPONSE = "ARTICLE_ERROR_RESPONSE";

export const ARTICLE_LIST = "ARTICLE_LIST";
export const ARTICLE_LIST_SUCCESS_RESPONSE = "ARTICLE_LIST_SUCCESS_RESPONSE";
export const ARTICLE_LIST_ERROR_RESPONSE = "ARTICLE_LIST_ERROR_RESPONSE";

export const LOGOUT = "LOGOUT";
