export const SIGNUP_USER = "SIGNUP_USER";
export const SIGNUP_USER_SERVER_RESPONSE_ERROR =
  "SIGNUP_USER_SERVER_RESPONSE_ERROR";
export const SIGNUP_USER_SERVER_RESPONSE_SUCCESS =
  "SIGNUP_USER_SERVER_RESPONSE_SUCCESS";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SERVER_RESPONSE_ERROR =
  "LOGIN_USER_SERVER_RESPONSE_ERROR";
export const LOGIN_USER_SERVER_RESPONSE_SUCCESS =
  "LOGIN_USER_SERVER_RESPONSE_SUCCESS";

export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const CREATE_ARTICLE_DETAILS_SERVER_RESPONSE_SUCCESS =
  "CREATE_ARTICLE_DETAILS_SERVER_RESPONSE_SUCCESS";
export const CREATE_ARTICLE_DETAILS_SERVER_RESPONSE_ERROR =
  "CREATE_ARTICLE_DETAILS_SERVER_RESPONSE_ERROR";

export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";

export const GET_ARTICLE_DETAILS = "GET_ARTICLE_DETAILS";
export const GET_ARTICLE_DETAILS_SERVER_RESPONSE_SUCCESS =
  "GET_ARTICLE_DETAILS_SERVER_RESPONSE_SUCCESS";
export const GET_ARTICLE_DETAILS_SERVER_RESPONSE_ERROR =
  "GET_ARTICLE_DETAILS_SERVER_RESPONSE_ERROR";

export const GET_ARTICLE_LIKES = "GET_ARTICLE_LIKES";
export const GET_ARTICLE_LIKES_SERVER_RESPONSE_SUCCESS =
  "GET_ARTICLE_LIKES_SERVER_RESPONSE_SUCCESS";
export const GET_ARTICLE_LIKES_SERVER_RESPONSE_ERROR =
  "GET_ARTICLE_LIKES_SERVER_RESPONSE_ERROR";

export const GET_ARTICLE_COMMENTS = "GET_ARTICLE_COMMENTS";
export const GET_ARTICLE_COMMENTS_SERVER_RESPONSE_SUCCESS =
  "GET_ARTICLE_COMMENTS_SERVER_RESPONSE_SUCCESS";
export const GET_ARTICLE_COMMENTS_SERVER_RESPONSE_ERROR =
  "GET_ARTICLE_COMMENTS_DETAILS_SERVER_RESPONSE_ERROR";

export const POST_COMMENT_ARTICLE = "POST_COMMENT_ARTICLE";
export const POST_COMMENT_ARTICLE_DETAILS_SERVER_RESPONSE_SUCCESS =
  "POST_COMMENT_ARTICLE_DETAILS_SERVER_RESPONSE_SUCCESS";
export const POST_COMMENT_ARTICLE_DETAILS_SERVER_RESPONSE_ERROR =
  "POST_COMMENT_ARTICLE_DETAILS_SERVER_RESPONSE_ERROR";

export const ARTICLE_LIST = "ARTICLE_LIST";
export const ARTICLE_LIST_SUCCESS_RESPONSE = "ARTICLE_LIST_SUCCESS_RESPONSE";
export const ARTICLE_LIST_ERROR_RESPONSE = "ARTICLE_LIST_ERROR_RESPONSE";

export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS_RESPONSE = "GET_USER_SUCCESS_RESPONSE";
export const GET_USER_ERROR_RESPONSE = "GET_USER_ERROR_RESPONSE";

export const GET_BOOKMARKS = "GET_BOOKMARKS";
export const GET_BOOKMARKS_SUCCESS_RESPONSE = "GET_BOOKMARKS_SUCCESS_RESPONSE";
export const GET_BOOKMARKS_ERROR_RESPONSE = "GET_BOOKMARKS_ERROR_RESPONSE";

export const FOLLOW_USER = "FOLLOW_USER";
export const FOLLOW_USER_SUCCESS_RESPONSE = "FOLLOW_USER_SUCCESS_RESPONSE";
export const FOLLOW_USER_ERROR_RESPONSE = "FOLLOW_USER_ERROR_RESPONSE";

export const UN_FOLLOW_USER = "UN_FOLLOW_USER";
export const UN_FOLLOW_USER_SUCCESS_RESPONSE =
  "UN_FOLLOW_USER_SUCCESS_RESPONSE";
export const UN_FOLLOW_USER_ERROR_RESPONSE = "UN_FOLLOW_USER_ERROR_RESPONSE";

export const BOOKMARK_ARTICLE = "BOOKMARK_ARTICLE";
export const BOOKMARK_ARTICLE_SUCCESS_RESPONSE =
  "BOOKMARK_ARTICLE_SUCCESS_RESPONSE";
export const BOOKMARK_ARTICLE_ERROR_RESPONSE =
  "BOOKMARK_ARTICLE_ERROR_RESPONSE";

export const UN_BOOKMARK_ARTICLE = "UN_BOOKMARK_ARTICLE";
export const UN_BOOKMARK_ARTICLE_SUCCESS_RESPONSE =
  "UN_BOOKMARK_ARTICLE_SUCCESS_RESPONSE";
export const UN_BOOKMARK_ARTICLE_ERROR_RESPONSE =
  "UN_BOOKMARK_ARTICLE_ERROR_RESPONSE";

export const LIKE_ARTICLE = "LIKE_ARTICLE";
export const LIKE_ARTICLE_SUCCESS_RESPONSE = "LIKE_ARTICLE_SUCCESS_RESPONSE";
export const LIKE_ARTICLE_ERROR_RESPONSE = "LIKE_ARTICLE_ERROR_RESPONSE";


export const DELETE_LIKE_ARTICLE = "DELETE_LIKE_ARTICLE";
export const DELETE_LIKE_ARTICLE_SUCCESS_RESPONSE = "DELETE_LIKE_ARTICLE_SUCCESS_RESPONSE";
export const DELETE_LIKE_ARTICLE_ERROR_RESPONSE = "DELETE_LIKE_ARTICLE_ERROR_RESPONSE";

export const GET_FOLLOWERS = "GET_FOLLOWERS";
export const GET_FOLLOWERS_SUCCESS_RESPONSE = "GET_FOLLOWERS_SUCCESS_RESPONSE";
export const GET_FOLLOWERS_ERROR_RESPONSE = "GET_FOLLOWERS_ERROR_RESPONSE";

export const GET_FOLLOWING = "GET_FOLLOWING";
export const GET_FOLLOWING_SUCCESS_RESPONSE = "GET_FOLLOWING_SUCCESS_RESPONSE";
export const GET_FOLLOWING_ERROR_RESPONSE = "GET_FOLLOWING_ERROR_RESPONSE";

export const GET_USER_WRITTEN_ARTICLES = "GET_USER_WRITTEN_ARTICLES";
export const GET_USER_WRITTEN_ARTICLES_SERVER_RESPONSE_SUCCESS =
  "GET_USER_WRITTEN_ARTICLES_SERVER_RESPONSE_SUCCESS";
export const GET_USER_WRITTEN_ARTICLES_SERVER_RESPONSE_ERROR =
  "GET_USER_WRITTEN_ARTICLES_SERVER_RESPONSE_ERROR";

export const USER_LOGOUT = "USER_LOGOUT";
